### ISSUE TITLE
Hide API keys and Tokens

### ISSUE THREAD

**Issue by DARK-art108** [DARK-art108/TellTodo#1]
**Is your feature request related to a problem? Please describe.**
As we know API Keys are prone to security vulnerability so we need to hide these API keys and Tokens.

**Describe the solution you'd like**
Refer to this article to add this enhancement [Hide your API and Tokens](https://medium.com/black-tech-diva/hide-your-api-keys-7635e181a06c)

**Comment by shikharcodes** [comment]
I would like to work on this issue @DARK-art108 .

**Comment by AnkurMishra123** [comment]
I would like to work on this issue.
You can slit the bot.py in part to hide API tokens and ignore it using .gitignore so that your API tokens file does not end up viewable on GitHub.

**Comment by AnkurMishra123** [comment]
I would like to work on this issue.
You can slit the bot.py in part to hide API tokens in another file and ignore it using .gitignore so that your API tokens file does not end up viewable on GitHub.

**Comment by DARK-art108** [comment]
Yeah Go Ahead Work on it raise PR when you have done!!
