### ISSUE TITLE
Dockerize the Project for Easy Setup

### ISSUE THREAD

**Issue by DARK-art108** [DARK-art108/TellTodo#2]
**Is your feature request related to a problem? Please describe.**
I think dockerizing the whole project will help us to run and set up the project in an easy way

**Describe the solution you'd like**
Create a Dockerfile, to automate the process.

**Comment by iamkrati22** [comment]
I would like to work on this issue.

**Comment by DARK-art108** [comment]
Yeah Sure @iamkrati22, Go Ahead!!
